"""user_fields

Revision ID: 25ffab062c36
Revises: 408ab71b6220
Create Date: 2024-04-25 00:23:26.154031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ffab062c36'
down_revision = '408ab71b6220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
