"""user_fields

Revision ID: 408ab71b6220
Revises: 887fface666d
Create Date: 2024-04-25 00:15:48.892651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408ab71b6220'
down_revision = '887fface666d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('middlename', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('business_sector', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('registration_no', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bvn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('home_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('local_government', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('local_government')
        batch_op.drop_column('state')
        batch_op.drop_column('home_address')
        batch_op.drop_column('business_address')
        batch_op.drop_column('bvn')
        batch_op.drop_column('registration_no')
        batch_op.drop_column('business_sector')
        batch_op.drop_column('business_name')
        batch_op.drop_column('dob')
        batch_op.drop_column('middlename')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
